
# Syntax highlighting
# markdown:            redcarpet
# highlighter:         pygments

# Permalinks
permalink:           :title
#relative_permalinks: true

# Setup
timezone:            your timezone # eg. Asia/Kathmandu
locale:              your locale language # eg. en_us
name:                AI et. al.
title:               AI et. al.
tagline:             'tagline'
description:         'On Artificial Intelligence and other stuff'
url:                 site url
# rss:                 rss feed url
baseurl:             '/AI-ET-AL/'
baseurl_posts_img:   '/AI-ET-AL/assets/images/posts/'
baseurl_featured_img: '/AI-ET-AL/assets/images/hero/'
baseurl_featured_thumbnail: '/AI-ET-AL/assets/images/thumbnail/'
baseurl_javascripts: '/AI-ET-AL/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:              Ahmad Mustapha
  url:               your site url
  twitter:           Ahmad__Mustapha
  linkedin:          ahmad-mustapha-ml
  email:             ahmad.m.mustapha@hotmail.com
  medium:            ahmad-mustapha

# fb_admins:           your facebook profile id
# fb_appid:            your facebook app id

# Server
destination:       ./_site
exclude:           [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:              9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
